- hosts: localhost
  vars_files:
    - files/vars.yaml
  tasks:
    - name: Update package manager
      become: true
      command:
        warn: false
        cmd: dnf update -y
    - name: Install packages
      become: true
      package:
        name:
          - util-linux-user
          - procps 
          - net-tools
          - neovim
          - git
          - gpg
          - tmux
          - zsh
          - ruby
          - ruby-devel
          - python3
          - golang
          - jq
          - make
          - git-credential-libsecret
          - podman
          - podman-compose
          - asciinema
    - name: Change shell to zsh
      become: true
      command: chsh -s /usr/bin/zsh
    - name: Set ZDOTDIR in zshenv
      lineinfile:
        dest: '~/.zshenv'
        regexp: 'export ZDOTDIR=~/.dotfiles/config/zsh'
        line: 'export ZDOTDIR=~/.dotfiles/config/zsh'
        create: true
    - name: Link configs that must be in XDG_CONFIG_HOME
      file:
        src: '~/.dotfiles/config/{{ item }}'
        dest: '~/.config/{{ item }}'
        state: link
        force: true
      loop:
        - git
    - name: Configure Git
      command: git config -f ~/.local/git/config {{ item }}
      loop:
        - user.name '{{ git.name }}'
        - user.email {{ git.email }}
    - name: Git pull submodules
      command:
        cmd: git pull --recurse-submodules
        chdir: ~/.dotfiles
